name: 'action-edge-addone-upload'
author: 'hocgin'
description: 'Microsoft Edge Add-ons Upload Action'
inputs:
  debug:
    description: 'debug mode'
  notes:
    description: 'addone publish notes'
  product_id:
    required: true
    description: 'addone product id'
  client_id:
    required: true
    description: 'Microsoft Edge Add-ons API client_id'
  client_secret:
    required: true
    description: 'Microsoft Edge Add-ons API client_secret'
  access_token_url:
    required: true
    description: 'Microsoft Edge Add-ons API access_token_url'
  addone_file:
    required: true
    description: 'Microsoft Edge Add-ons API addone_file'
  upload_only:
    required: false
    description: '仅上传'
    default: false
runs:
  using: node16
  main: dist/index.js
